spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/db
    username: postgres
    password: root
    hikari:
      schema: exam
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate #validate
server:
  port: 8981